services:
  server:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          NODE_ENV: "production"
          NEXT_PUBLIC_SANITY_PROJECT_ID: "muy92sh0"
          NEXT_PUBLIC_SANITY_DATASET: "production"
          NEXT_PUBLIC_SANITY_API_VERSION: "vX"
    env_file:
        - .env
    volumes:
      - .:/app
    ports:
        - 8000:8000