- name: Deploy to EC2
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      cd ${{ secrets.EC2_DEPLOY_PATH }}
      git checkout -f
      git pull origin master
      rm -rf node_modules
      rm -rf .next
      rsync -avz --exclude=".git" ./ /var/www/startups-directory/
      cd /var/www/startups-directory
      npm install --production
      npm run build
      pm2 restart startups-directory || pm2 start npm --name startups-directory -- start
