name: Production Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to staging
      uses: appleboy/ssh-action@master
      env:
        SSH_BUILD_DIRECTORY: ${{ secrets.EC2_DEPLOY_PATH }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: SSH_BUILD_DIRECTORY
        script: |
          cd $SSH_BUILD_DIRECTORY

          echo "Pulling latest code"
          git checkout -f
          git pull origin master

